env:
  img_size: 200
  aircraft_detection_range: 100
  max_time_step: 100
  time_scaling: 25
goal_tolerance: 25.0
goal_reward: 100.0
time_limit_penalty: -100.0
load_data_num: 1000  # How many trajectories to load.
output_path:  /home/lucas/Workspace/CORL/data/ #/media/lucas/T7/Offline_rl_data/ # Where to store the processed data.