info:
  name: SAC_rlpd
  project: Evasion Planning
  seed: 0

train:
  num_envs: 10
  batch_size: 64
  buffer_size: 36212 # 36212
  data_path: /home/yixuany/workspace/CORL/finetune_data_sac_risk_measure/
  checkpoints_path: /home/yixuany/workspace/CORL/output
  device: cuda
  discount: 0.99

  total_timesteps: 3_000_000
  learning_starts: 500
  policy_frequency: 2
  target_network_frequency: 1
  policy_lr: 0.0003  # Actor learning rate
  q_lr: 0.001

  gamma: 0.99
  tau: 0.005

  policy_specs:
    actor_net_hidden: [64, 64]
    hidden_act: ReLU

eval:
  eval_freq: 12_000
  n_episodes: 5
  seed: 0


env:
  map_size: 1000
  V: 30.0
  delta_t: 0.5
  radar_radius: 75
  aircraft_detection_range: 100
  img_size: 100
  action_dim: 1
  action_normalized: True  #### If true, actions are normalized to [-1, 1]
  action_min: -36.0
  action_max: 36.0
  max_time_step: 500
  goal_tolerance: 30.0
  reward_normalization_factor: 100
  interceptor_launch_time: 10
  interceptor_abort_time: 3
  observation:
    heat_map_normalized: False
    goal_direction_normalized: True
    time_scaling: 25